name: webview_cookie_manager_flutter
description: Have you been turned into a cookie management problem? This package can help. It has all of the cookie management functionality you have been looking for.
version: 3.0.1
repository: https://github.com/rezwanahmedsami/webview_cookie_manager_flutter
homepage: https://github.com/rezwanahmedsami/webview_cookie_manager_flutter
issue_tracker: https://github.com/rezwanahmedsami/webview_cookie_manager_flutter/issues

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.webview_cookie_manager
        pluginClass: WebviewCookieManagerPlugin
      ios:
        pluginClass: WebviewCookieManagerPlugin
